#ifndef TWEETNACL_H
#define TWEETNACL_H
#define tweet_auth_PRIMITIVE "hmacsha512256"
#define tweet_auth tweet_auth_hmacsha512256
#define tweet_auth_verify tweet_auth_hmacsha512256_verify
#define tweet_auth_BYTES tweet_auth_hmacsha512256_BYTES
#define tweet_auth_KEYBYTES tweet_auth_hmacsha512256_KEYBYTES
#define tweet_auth_IMPLEMENTATION tweet_auth_hmacsha512256_IMPLEMENTATION
#define tweet_auth_VERSION tweet_auth_hmacsha512256_VERSION
#define tweet_auth_hmacsha512256_crypto_BYTES 32
#define tweet_auth_hmacsha512256_crypto_KEYBYTES 32
extern int tweet_auth_hmacsha512256_crypto(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *);
extern int tweet_auth_hmacsha512256_crypto_verify(const unsigned char *,const unsigned char *,unsigned long long,const unsigned char *);
#define tweet_auth_hmacsha512256_crypto_VERSION "-"
#define tweet_auth_hmacsha512256 tweet_auth_hmacsha512256_crypto
#define tweet_auth_hmacsha512256_verify tweet_auth_hmacsha512256_crypto_verify
#define tweet_auth_hmacsha512256_BYTES tweet_auth_hmacsha512256_crypto_BYTES
#define tweet_auth_hmacsha512256_KEYBYTES tweet_auth_hmacsha512256_crypto_KEYBYTES
#define tweet_auth_hmacsha512256_VERSION tweet_auth_hmacsha512256_crypto_VERSION
#define tweet_auth_hmacsha512256_IMPLEMENTATION "tweet_auth/hmacsha512256/tweet"
#define tweet_box_PRIMITIVE "curve25519xsalsa20poly1305"
#define tweet_box tweet_box_curve25519xsalsa20poly1305
#define tweet_box_open tweet_box_curve25519xsalsa20poly1305_open
#define tweet_box_keypair tweet_box_curve25519xsalsa20poly1305_keypair
#define tweet_box_beforenm tweet_box_curve25519xsalsa20poly1305_beforenm
#define tweet_box_afternm tweet_box_curve25519xsalsa20poly1305_afternm
#define tweet_box_open_afternm tweet_box_curve25519xsalsa20poly1305_open_afternm
#define tweet_box_PUBLICKEYBYTES tweet_box_curve25519xsalsa20poly1305_PUBLICKEYBYTES
#define tweet_box_SECRETKEYBYTES tweet_box_curve25519xsalsa20poly1305_SECRETKEYBYTES
#define tweet_box_BEFORENMBYTES tweet_box_curve25519xsalsa20poly1305_BEFORENMBYTES
#define tweet_box_NONCEBYTES tweet_box_curve25519xsalsa20poly1305_NONCEBYTES
#define tweet_box_ZEROBYTES tweet_box_curve25519xsalsa20poly1305_ZEROBYTES
#define tweet_box_BOXZEROBYTES tweet_box_curve25519xsalsa20poly1305_BOXZEROBYTES
#define tweet_box_IMPLEMENTATION tweet_box_curve25519xsalsa20poly1305_IMPLEMENTATION
#define tweet_box_VERSION tweet_box_curve25519xsalsa20poly1305_VERSION
#define tweet_box_curve25519xsalsa20poly1305_crypto_PUBLICKEYBYTES 32
#define tweet_box_curve25519xsalsa20poly1305_crypto_SECRETKEYBYTES 32
#define tweet_box_curve25519xsalsa20poly1305_crypto_BEFORENMBYTES 32
#define tweet_box_curve25519xsalsa20poly1305_crypto_NONCEBYTES 24
#define tweet_box_curve25519xsalsa20poly1305_crypto_ZEROBYTES 32
#define tweet_box_curve25519xsalsa20poly1305_crypto_BOXZEROBYTES 16
extern int tweet_box_curve25519xsalsa20poly1305_crypto(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *,const unsigned char *);
extern int tweet_box_curve25519xsalsa20poly1305_crypto_open(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *,const unsigned char *);
extern int tweet_box_curve25519xsalsa20poly1305_crypto_keypair(unsigned char *,unsigned char *);
extern int tweet_box_curve25519xsalsa20poly1305_crypto_beforenm(unsigned char *,const unsigned char *,const unsigned char *);
extern int tweet_box_curve25519xsalsa20poly1305_crypto_afternm(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
extern int tweet_box_curve25519xsalsa20poly1305_crypto_open_afternm(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
#define tweet_box_curve25519xsalsa20poly1305_crypto_VERSION "-"
#define tweet_box_curve25519xsalsa20poly1305 tweet_box_curve25519xsalsa20poly1305_crypto
#define tweet_box_curve25519xsalsa20poly1305_open tweet_box_curve25519xsalsa20poly1305_crypto_open
#define tweet_box_curve25519xsalsa20poly1305_keypair tweet_box_curve25519xsalsa20poly1305_crypto_keypair
#define tweet_box_curve25519xsalsa20poly1305_beforenm tweet_box_curve25519xsalsa20poly1305_crypto_beforenm
#define tweet_box_curve25519xsalsa20poly1305_afternm tweet_box_curve25519xsalsa20poly1305_crypto_afternm
#define tweet_box_curve25519xsalsa20poly1305_open_afternm tweet_box_curve25519xsalsa20poly1305_crypto_open_afternm
#define tweet_box_curve25519xsalsa20poly1305_PUBLICKEYBYTES tweet_box_curve25519xsalsa20poly1305_crypto_PUBLICKEYBYTES
#define tweet_box_curve25519xsalsa20poly1305_SECRETKEYBYTES tweet_box_curve25519xsalsa20poly1305_crypto_SECRETKEYBYTES
#define tweet_box_curve25519xsalsa20poly1305_BEFORENMBYTES tweet_box_curve25519xsalsa20poly1305_crypto_BEFORENMBYTES
#define tweet_box_curve25519xsalsa20poly1305_NONCEBYTES tweet_box_curve25519xsalsa20poly1305_crypto_NONCEBYTES
#define tweet_box_curve25519xsalsa20poly1305_ZEROBYTES tweet_box_curve25519xsalsa20poly1305_crypto_ZEROBYTES
#define tweet_box_curve25519xsalsa20poly1305_BOXZEROBYTES tweet_box_curve25519xsalsa20poly1305_crypto_BOXZEROBYTES
#define tweet_box_curve25519xsalsa20poly1305_VERSION tweet_box_curve25519xsalsa20poly1305_crypto_VERSION
#define tweet_box_curve25519xsalsa20poly1305_IMPLEMENTATION "tweet_box/curve25519xsalsa20poly1305/tweet"
#define tweet_core_PRIMITIVE "salsa20"
#define tweet_core tweet_core_salsa20
#define tweet_core_OUTPUTBYTES tweet_core_salsa20_OUTPUTBYTES
#define tweet_core_INPUTBYTES tweet_core_salsa20_INPUTBYTES
#define tweet_core_KEYBYTES tweet_core_salsa20_KEYBYTES
#define tweet_core_CONSTBYTES tweet_core_salsa20_CONSTBYTES
#define tweet_core_IMPLEMENTATION tweet_core_salsa20_IMPLEMENTATION
#define tweet_core_VERSION tweet_core_salsa20_VERSION
#define tweet_core_salsa20_crypto_OUTPUTBYTES 64
#define tweet_core_salsa20_crypto_INPUTBYTES 16
#define tweet_core_salsa20_crypto_KEYBYTES 32
#define tweet_core_salsa20_crypto_CONSTBYTES 16
extern int tweet_core_salsa20_crypto(unsigned char *,const unsigned char *,const unsigned char *,const unsigned char *);
#define tweet_core_salsa20_crypto_VERSION "-"
#define tweet_core_salsa20 tweet_core_salsa20_crypto
#define tweet_core_salsa20_OUTPUTBYTES tweet_core_salsa20_crypto_OUTPUTBYTES
#define tweet_core_salsa20_INPUTBYTES tweet_core_salsa20_crypto_INPUTBYTES
#define tweet_core_salsa20_KEYBYTES tweet_core_salsa20_crypto_KEYBYTES
#define tweet_core_salsa20_CONSTBYTES tweet_core_salsa20_crypto_CONSTBYTES
#define tweet_core_salsa20_VERSION tweet_core_salsa20_crypto_VERSION
#define tweet_core_salsa20_IMPLEMENTATION "tweet_core/salsa20/tweet"
#define tweet_core_hsalsa20_crypto_OUTPUTBYTES 32
#define tweet_core_hsalsa20_crypto_INPUTBYTES 16
#define tweet_core_hsalsa20_crypto_KEYBYTES 32
#define tweet_core_hsalsa20_crypto_CONSTBYTES 16
extern int tweet_core_hsalsa20_crypto(unsigned char *,const unsigned char *,const unsigned char *,const unsigned char *);
#define tweet_core_hsalsa20_crypto_VERSION "-"
#define tweet_core_hsalsa20 tweet_core_hsalsa20_crypto
#define tweet_core_hsalsa20_OUTPUTBYTES tweet_core_hsalsa20_crypto_OUTPUTBYTES
#define tweet_core_hsalsa20_INPUTBYTES tweet_core_hsalsa20_crypto_INPUTBYTES
#define tweet_core_hsalsa20_KEYBYTES tweet_core_hsalsa20_crypto_KEYBYTES
#define tweet_core_hsalsa20_CONSTBYTES tweet_core_hsalsa20_crypto_CONSTBYTES
#define tweet_core_hsalsa20_VERSION tweet_core_hsalsa20_crypto_VERSION
#define tweet_core_hsalsa20_IMPLEMENTATION "tweet_core/hsalsa20/tweet"
#define tweet_hashblocks_PRIMITIVE "sha512"
#define tweet_hashblocks tweet_hashblocks_sha512
#define tweet_hashblocks_STATEBYTES tweet_hashblocks_sha512_STATEBYTES
#define tweet_hashblocks_BLOCKBYTES tweet_hashblocks_sha512_BLOCKBYTES
#define tweet_hashblocks_IMPLEMENTATION tweet_hashblocks_sha512_IMPLEMENTATION
#define tweet_hashblocks_VERSION tweet_hashblocks_sha512_VERSION
#define tweet_hashblocks_sha512_crypto_STATEBYTES 64
#define tweet_hashblocks_sha512_crypto_BLOCKBYTES 128
extern int tweet_hashblocks_sha512_crypto(unsigned char *,const unsigned char *,unsigned long long);
#define tweet_hashblocks_sha512_crypto_VERSION "-"
#define tweet_hashblocks_sha512 tweet_hashblocks_sha512_crypto
#define tweet_hashblocks_sha512_STATEBYTES tweet_hashblocks_sha512_crypto_STATEBYTES
#define tweet_hashblocks_sha512_BLOCKBYTES tweet_hashblocks_sha512_crypto_BLOCKBYTES
#define tweet_hashblocks_sha512_VERSION tweet_hashblocks_sha512_crypto_VERSION
#define tweet_hashblocks_sha512_IMPLEMENTATION "tweet_hashblocks/sha512/tweet"
#define tweet_hashblocks_sha256_crypto_STATEBYTES 32
#define tweet_hashblocks_sha256_crypto_BLOCKBYTES 64
extern int tweet_hashblocks_sha256_crypto(unsigned char *,const unsigned char *,unsigned long long);
#define tweet_hashblocks_sha256_crypto_VERSION "-"
#define tweet_hashblocks_sha256 tweet_hashblocks_sha256_crypto
#define tweet_hashblocks_sha256_STATEBYTES tweet_hashblocks_sha256_crypto_STATEBYTES
#define tweet_hashblocks_sha256_BLOCKBYTES tweet_hashblocks_sha256_crypto_BLOCKBYTES
#define tweet_hashblocks_sha256_VERSION tweet_hashblocks_sha256_crypto_VERSION
#define tweet_hashblocks_sha256_IMPLEMENTATION "tweet_hashblocks/sha256/tweet"
#define tweet_hash_PRIMITIVE "sha512"
#define tweet_hash tweet_hash_sha512
#define tweet_hash_BYTES tweet_hash_sha512_BYTES
#define tweet_hash_IMPLEMENTATION tweet_hash_sha512_IMPLEMENTATION
#define tweet_hash_VERSION tweet_hash_sha512_VERSION
#define tweet_hash_sha512_crypto_BYTES 64
extern int tweet_hash_sha512_crypto(unsigned char *,const unsigned char *,unsigned long long);
#define tweet_hash_sha512_crypto_VERSION "-"
#define tweet_hash_sha512 tweet_hash_sha512_crypto
#define tweet_hash_sha512_BYTES tweet_hash_sha512_crypto_BYTES
#define tweet_hash_sha512_VERSION tweet_hash_sha512_crypto_VERSION
#define tweet_hash_sha512_IMPLEMENTATION "tweet_hash/sha512/tweet"
#define tweet_hash_sha256_crypto_BYTES 32
extern int tweet_hash_sha256_crypto(unsigned char *,const unsigned char *,unsigned long long);
#define tweet_hash_sha256_crypto_VERSION "-"
#define tweet_hash_sha256 tweet_hash_sha256_crypto
#define tweet_hash_sha256_BYTES tweet_hash_sha256_crypto_BYTES
#define tweet_hash_sha256_VERSION tweet_hash_sha256_crypto_VERSION
#define tweet_hash_sha256_IMPLEMENTATION "tweet_hash/sha256/tweet"
#define tweet_onetimeauth_PRIMITIVE "poly1305"
#define tweet_onetimeauth tweet_onetimeauth_poly1305
#define tweet_onetimeauth_verify tweet_onetimeauth_poly1305_verify
#define tweet_onetimeauth_BYTES tweet_onetimeauth_poly1305_BYTES
#define tweet_onetimeauth_KEYBYTES tweet_onetimeauth_poly1305_KEYBYTES
#define tweet_onetimeauth_IMPLEMENTATION tweet_onetimeauth_poly1305_IMPLEMENTATION
#define tweet_onetimeauth_VERSION tweet_onetimeauth_poly1305_VERSION
#define tweet_onetimeauth_poly1305_crypto_BYTES 16
#define tweet_onetimeauth_poly1305_crypto_KEYBYTES 32
extern int tweet_onetimeauth_poly1305_crypto(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *);
extern int tweet_onetimeauth_poly1305_crypto_verify(const unsigned char *,const unsigned char *,unsigned long long,const unsigned char *);
#define tweet_onetimeauth_poly1305_crypto_VERSION "-"
#define tweet_onetimeauth_poly1305 tweet_onetimeauth_poly1305_crypto
#define tweet_onetimeauth_poly1305_verify tweet_onetimeauth_poly1305_crypto_verify
#define tweet_onetimeauth_poly1305_BYTES tweet_onetimeauth_poly1305_crypto_BYTES
#define tweet_onetimeauth_poly1305_KEYBYTES tweet_onetimeauth_poly1305_crypto_KEYBYTES
#define tweet_onetimeauth_poly1305_VERSION tweet_onetimeauth_poly1305_crypto_VERSION
#define tweet_onetimeauth_poly1305_IMPLEMENTATION "tweet_onetimeauth/poly1305/tweet"
#define tweet_scalarmult_PRIMITIVE "curve25519"
#define tweet_scalarmult tweet_scalarmult_curve25519
#define tweet_scalarmult_base tweet_scalarmult_curve25519_base
#define tweet_scalarmult_BYTES tweet_scalarmult_curve25519_BYTES
#define tweet_scalarmult_SCALARBYTES tweet_scalarmult_curve25519_SCALARBYTES
#define tweet_scalarmult_IMPLEMENTATION tweet_scalarmult_curve25519_IMPLEMENTATION
#define tweet_scalarmult_VERSION tweet_scalarmult_curve25519_VERSION
#define tweet_scalarmult_curve25519_crypto_BYTES 32
#define tweet_scalarmult_curve25519_crypto_SCALARBYTES 32
extern int tweet_scalarmult_curve25519_crypto(unsigned char *,const unsigned char *,const unsigned char *);
extern int tweet_scalarmult_curve25519_crypto_base(unsigned char *,const unsigned char *);
#define tweet_scalarmult_curve25519_crypto_VERSION "-"
#define tweet_scalarmult_curve25519 tweet_scalarmult_curve25519_crypto
#define tweet_scalarmult_curve25519_base tweet_scalarmult_curve25519_crypto_base
#define tweet_scalarmult_curve25519_BYTES tweet_scalarmult_curve25519_crypto_BYTES
#define tweet_scalarmult_curve25519_SCALARBYTES tweet_scalarmult_curve25519_crypto_SCALARBYTES
#define tweet_scalarmult_curve25519_VERSION tweet_scalarmult_curve25519_crypto_VERSION
#define tweet_scalarmult_curve25519_IMPLEMENTATION "tweet_scalarmult/curve25519/tweet"
#define tweet_secretbox_PRIMITIVE "xsalsa20poly1305"
#define tweet_secretbox tweet_secretbox_xsalsa20poly1305
#define tweet_secretbox_open tweet_secretbox_xsalsa20poly1305_open
#define tweet_secretbox_KEYBYTES tweet_secretbox_xsalsa20poly1305_KEYBYTES
#define tweet_secretbox_NONCEBYTES tweet_secretbox_xsalsa20poly1305_NONCEBYTES
#define tweet_secretbox_ZEROBYTES tweet_secretbox_xsalsa20poly1305_ZEROBYTES
#define tweet_secretbox_BOXZEROBYTES tweet_secretbox_xsalsa20poly1305_BOXZEROBYTES
#define tweet_secretbox_IMPLEMENTATION tweet_secretbox_xsalsa20poly1305_IMPLEMENTATION
#define tweet_secretbox_VERSION tweet_secretbox_xsalsa20poly1305_VERSION
#define tweet_secretbox_xsalsa20poly1305_crypto_KEYBYTES 32
#define tweet_secretbox_xsalsa20poly1305_crypto_NONCEBYTES 24
#define tweet_secretbox_xsalsa20poly1305_crypto_ZEROBYTES 32
#define tweet_secretbox_xsalsa20poly1305_crypto_BOXZEROBYTES 16
extern int tweet_secretbox_xsalsa20poly1305_crypto(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
extern int tweet_secretbox_xsalsa20poly1305_crypto_open(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
#define tweet_secretbox_xsalsa20poly1305_crypto_VERSION "-"
#define tweet_secretbox_xsalsa20poly1305 tweet_secretbox_xsalsa20poly1305_crypto
#define tweet_secretbox_xsalsa20poly1305_open tweet_secretbox_xsalsa20poly1305_crypto_open
#define tweet_secretbox_xsalsa20poly1305_KEYBYTES tweet_secretbox_xsalsa20poly1305_crypto_KEYBYTES
#define tweet_secretbox_xsalsa20poly1305_NONCEBYTES tweet_secretbox_xsalsa20poly1305_crypto_NONCEBYTES
#define tweet_secretbox_xsalsa20poly1305_ZEROBYTES tweet_secretbox_xsalsa20poly1305_crypto_ZEROBYTES
#define tweet_secretbox_xsalsa20poly1305_BOXZEROBYTES tweet_secretbox_xsalsa20poly1305_crypto_BOXZEROBYTES
#define tweet_secretbox_xsalsa20poly1305_VERSION tweet_secretbox_xsalsa20poly1305_crypto_VERSION
#define tweet_secretbox_xsalsa20poly1305_IMPLEMENTATION "tweet_secretbox/xsalsa20poly1305/tweet"
#define tweet_sign_PRIMITIVE "ed25519"
#define tweet_sign tweet_sign_ed25519
#define tweet_sign_open tweet_sign_ed25519_open
#define tweet_sign_keypair tweet_sign_ed25519_keypair
#define tweet_sign_BYTES tweet_sign_ed25519_BYTES
#define tweet_sign_PUBLICKEYBYTES tweet_sign_ed25519_PUBLICKEYBYTES
#define tweet_sign_SECRETKEYBYTES tweet_sign_ed25519_SECRETKEYBYTES
#define tweet_sign_IMPLEMENTATION tweet_sign_ed25519_IMPLEMENTATION
#define tweet_sign_VERSION tweet_sign_ed25519_VERSION
#define tweet_sign_ed25519_crypto_BYTES 64
#define tweet_sign_ed25519_crypto_PUBLICKEYBYTES 32
#define tweet_sign_ed25519_crypto_SECRETKEYBYTES 64
extern int tweet_sign_ed25519_crypto(unsigned char *,unsigned long long *,const unsigned char *,unsigned long long,const unsigned char *);
extern int tweet_sign_ed25519_crypto_open(unsigned char *,unsigned long long *,const unsigned char *,unsigned long long,const unsigned char *);
extern int tweet_sign_ed25519_crypto_keypair(unsigned char *,unsigned char *);
#define tweet_sign_ed25519_crypto_VERSION "-"
#define tweet_sign_ed25519 tweet_sign_ed25519_crypto
#define tweet_sign_ed25519_open tweet_sign_ed25519_crypto_open
#define tweet_sign_ed25519_keypair tweet_sign_ed25519_crypto_keypair
#define tweet_sign_ed25519_BYTES tweet_sign_ed25519_crypto_BYTES
#define tweet_sign_ed25519_PUBLICKEYBYTES tweet_sign_ed25519_crypto_PUBLICKEYBYTES
#define tweet_sign_ed25519_SECRETKEYBYTES tweet_sign_ed25519_crypto_SECRETKEYBYTES
#define tweet_sign_ed25519_VERSION tweet_sign_ed25519_crypto_VERSION
#define tweet_sign_ed25519_IMPLEMENTATION "tweet_sign/ed25519/tweet"
#define tweet_stream_PRIMITIVE "xsalsa20"
#define tweet_stream tweet_stream_xsalsa20
#define tweet_stream_xor tweet_stream_xsalsa20_xor
#define tweet_stream_KEYBYTES tweet_stream_xsalsa20_KEYBYTES
#define tweet_stream_NONCEBYTES tweet_stream_xsalsa20_NONCEBYTES
#define tweet_stream_IMPLEMENTATION tweet_stream_xsalsa20_IMPLEMENTATION
#define tweet_stream_VERSION tweet_stream_xsalsa20_VERSION
#define tweet_stream_xsalsa20_crypto_KEYBYTES 32
#define tweet_stream_xsalsa20_crypto_NONCEBYTES 24
extern int tweet_stream_xsalsa20_crypto(unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
extern int tweet_stream_xsalsa20_crypto_xor(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
#define tweet_stream_xsalsa20_crypto_VERSION "-"
#define tweet_stream_xsalsa20 tweet_stream_xsalsa20_crypto
#define tweet_stream_xsalsa20_xor tweet_stream_xsalsa20_crypto_xor
#define tweet_stream_xsalsa20_KEYBYTES tweet_stream_xsalsa20_crypto_KEYBYTES
#define tweet_stream_xsalsa20_NONCEBYTES tweet_stream_xsalsa20_crypto_NONCEBYTES
#define tweet_stream_xsalsa20_VERSION tweet_stream_xsalsa20_crypto_VERSION
#define tweet_stream_xsalsa20_IMPLEMENTATION "tweet_stream/xsalsa20/tweet"
#define tweet_stream_salsa20_crypto_KEYBYTES 32
#define tweet_stream_salsa20_crypto_NONCEBYTES 8
extern int tweet_stream_salsa20_crypto(unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
extern int tweet_stream_salsa20_crypto_xor(unsigned char *,const unsigned char *,unsigned long long,const unsigned char *,const unsigned char *);
#define tweet_stream_salsa20_crypto_VERSION "-"
#define tweet_stream_salsa20 tweet_stream_salsa20_crypto
#define tweet_stream_salsa20_xor tweet_stream_salsa20_crypto_xor
#define tweet_stream_salsa20_KEYBYTES tweet_stream_salsa20_crypto_KEYBYTES
#define tweet_stream_salsa20_NONCEBYTES tweet_stream_salsa20_crypto_NONCEBYTES
#define tweet_stream_salsa20_VERSION tweet_stream_salsa20_crypto_VERSION
#define tweet_stream_salsa20_IMPLEMENTATION "tweet_stream/salsa20/tweet"
#define tweet_verify_PRIMITIVE "16"
#define tweet_verify tweet_verify_16
#define tweet_verify_BYTES tweet_verify_16_BYTES
#define tweet_verify_IMPLEMENTATION tweet_verify_16_IMPLEMENTATION
#define tweet_verify_VERSION tweet_verify_16_VERSION
#define tweet_verify_16_crypto_BYTES 16
extern int tweet_verify_16_crypto(const unsigned char *,const unsigned char *);
#define tweet_verify_16_crypto_VERSION "-"
#define tweet_verify_16 tweet_verify_16_crypto
#define tweet_verify_16_BYTES tweet_verify_16_crypto_BYTES
#define tweet_verify_16_VERSION tweet_verify_16_crypto_VERSION
#define tweet_verify_16_IMPLEMENTATION "tweet_verify/16/tweet"
#define tweet_verify_32_crypto_BYTES 32
extern int tweet_verify_32_crypto(const unsigned char *,const unsigned char *);
#define tweet_verify_32_crypto_VERSION "-"
#define tweet_verify_32 tweet_verify_32_crypto
#define tweet_verify_32_BYTES tweet_verify_32_crypto_BYTES
#define tweet_verify_32_VERSION tweet_verify_32_crypto_VERSION
#define tweet_verify_32_IMPLEMENTATION "tweet_verify/32/tweet"
#endif
